// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBba4bl5WkfrWaluFrpID1v2P7Sh6zKEzQ',
    appId: '1:596539728562:web:58fc2e3a149b4d3d885fab',
    messagingSenderId: '596539728562',
    projectId: 'giycik-a350a',
    authDomain: 'giycik-a350a.firebaseapp.com',
    storageBucket: 'giycik-a350a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTi58OSHJ6MSrelJ4BIjwbrCMmgtjKfNU',
    appId: '1:596539728562:android:8524bc9647be3ed3885fab',
    messagingSenderId: '596539728562',
    projectId: 'giycik-a350a',
    storageBucket: 'giycik-a350a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvWCdOzvN7cS4CWN0gmUy5blQn_5C1x0',
    appId: '1:596539728562:ios:e9e3f12b9f8dcbd5885fab',
    messagingSenderId: '596539728562',
    projectId: 'giycik-a350a',
    storageBucket: 'giycik-a350a.firebasestorage.app',
    iosBundleId: 'com.example.gircik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvWCdOzvN7cS4CWN0gmUy5blQn_5C1x0',
    appId: '1:596539728562:ios:e9e3f12b9f8dcbd5885fab',
    messagingSenderId: '596539728562',
    projectId: 'giycik-a350a',
    storageBucket: 'giycik-a350a.firebasestorage.app',
    iosBundleId: 'com.example.gircik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBba4bl5WkfrWaluFrpID1v2P7Sh6zKEzQ',
    appId: '1:596539728562:web:46c5ed360a4c8a53885fab',
    messagingSenderId: '596539728562',
    projectId: 'giycik-a350a',
    authDomain: 'giycik-a350a.firebaseapp.com',
    storageBucket: 'giycik-a350a.firebasestorage.app',
  );
}
